[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 17

[studio]
enabled = true
port = 54323

[auth]
enabled = true
site_url = "https://demanddig.vercel.app"
additional_redirect_urls = ["https://demanddig.vercel.app"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[auth.external.github]
enabled = true
client_id = "env(GITHUB_CLIENT_ID)"
secret = "env(GITHUB_CLIENT_SECRET)"
redirect_uri = ""

[edge_runtime]
enabled = true

[functions.crawl-github]
verify_jwt = false

[functions.crawl-reddit]
verify_jwt = false

[functions.run-scorer]
verify_jwt = false
